FROM openjdk:17-alpine
VOLUME /tmp 
COPY target/NHPSAppApiPatients-0.0.1-SNAPSHOT.jar patients-microservice.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/patients-microservice.jar"]
